### ISSUE TITLE
Support Jetpack Preference Datastore

### ISSUE THREAD

**Issue by VincentJoshuaET** [EdwarDDay/serialization.kprefs#22]

**Comment by EdwarDDay** [comment]
Nice idea. Can you give an example, how you would like to use kprefs and Jetpack Datastore together?

**Comment by EdwarDDay** [comment]
I looked into it and I don't think, that this would be very feasible, because the Jetpack Preference Datastore works on Protobuf files. So a bette approach would be to directly use the Protobuf version with a typed Settings class or an extra DataStore per preference.
I created a small example which would show the usage of kotlinx.serialization for Jetpack DataStores:
https://gist.github.com/EdwarDDay/69835e59b79fe8d9135c867d00079c44
This can probably improved in the future, when kotlinx.serialization supports InputStream and OutputStream.
